DROP TABLE IF EXISTS audit_logs CASCADE;

DROP TABLE IF EXISTS social_connections CASCADE;

DROP TABLE IF EXISTS sessions CASCADE;

DROP TABLE IF EXISTS authorization_codes CASCADE;

DROP TABLE IF EXISTS refresh_tokens CASCADE;

DROP TABLE IF EXISTS user_permissions CASCADE;

DROP TABLE IF EXISTS user_roles CASCADE;

DROP TABLE IF EXISTS role_permissions CASCADE;

DROP TABLE IF EXISTS permissions CASCADE;

DROP TABLE IF EXISTS roles CASCADE;

DROP TABLE IF EXISTS oauth_clients CASCADE;

DROP TABLE IF EXISTS users CASCADE;
