package domain

import "errors"

var (
	ErrNotFound           = errors.New("not found")
	ErrConflict           = errors.New("conflict")
	ErrOptimisticLock     = errors.New("optimistic lock conflict")
	ErrDuplicateEmail     = errors.New("email already exists")
	ErrInvalidCredentials = errors.New("invalid credentials")
	ErrAccountLocked      = errors.New("account locked")
	ErrAccountUnverified  = errors.New("account unverified")
	ErrAccountDeleted     = errors.New("account deleted")
	ErrTokenExpired       = errors.New("token expired")
	ErrTokenRevoked       = errors.New("token revoked")
	ErrTokenReused        = errors.New("token reused")
	ErrInvalidToken       = errors.New("invalid token")
	ErrMFARequired         = errors.New("mfa required")
	ErrMFAAlreadyEnabled   = errors.New("mfa already enabled")
	ErrMFANotEnabled       = errors.New("mfa not enabled")
	ErrInvalidMFACode      = errors.New("invalid mfa code")
	ErrInvalidRecoveryCode = errors.New("invalid recovery code")
	ErrRateLimited        = errors.New("rate limited")
	ErrForbidden          = errors.New("forbidden")
	ErrCyclicRole         = errors.New("cyclic role hierarchy")
	ErrMaxDepthExceeded   = errors.New("max role depth exceeded")
	ErrInvalidRedirectURI = errors.New("invalid redirect uri")
	ErrInvalidScope       = errors.New("invalid scope")
	ErrInvalidGrantType   = errors.New("invalid grant type")
	ErrInvalidClient      = errors.New("invalid client")
	ErrCodeReuse          = errors.New("authorization code reuse detected")
	ErrPasswordTooShort   = errors.New("password too short")
	ErrPasswordTooLong    = errors.New("password too long")
)
